name: Pull and Run Docker Image

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow on

jobs:
  pull:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: "kirantm"
          password: "Coep.3596"

      - name: Pull Docker Image
        run: docker pull kirantm/ci-cd:v1
  
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: "kirantm"
          password: "Coep.3596"
          
      - name: Run Docker Container
        run: docker run --rm kirantm/ci-cd:v1
